version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace:cached
    environment:
      - OPENAI_API_KEY=OPENAI_API_KEY
    working_dir: /workspace
    tty: true
    ports:
      - '8501:8501'
    command: poetry run streamlit run streamlit_sandbox/index.py
